trigger:
- master
- tags

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'tests'
    arguments: '-c Release'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: 'src/*.fsproj'
    includesymbols: true
    versioningScheme: 'off'
    verbosityPack: 'Normal'

- script: dotnet nuget push -s  https://api.nuget.org/v3/index.json -k $(nuget-api-key) $(Build.ArtifactStagingDirectory)/*.nupkg
