trigger:
- master
- tags

variables:
  PKG_VAR: ${{ variables['Build.SourceBranchName'] }}

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreCLI@2
  name: 'test'
  inputs:
    command: 'test'
    projects: 'tests'
    arguments: '-c Release'

- task: DotNetCoreCLI@2
  name: 'pack'
  inputs:
    command: 'pack'
    packagesToPack: 'src/*.fsproj'
    includesymbols: true
- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: 'src/*.fsproj'
    includesymbols: true
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'PKG_VER'
    verbosityPack: 'Normal'

- script: dotnet nuget push -s  https://api.nuget.org/v3/index.json -k $(nuget-api-key) $(Build.ArtifactStagingDirectory)/*.nupkg
  name: 'push'
  condition: ${{ startsWith(variables['Build.SourceBranch'], 'refs/tags/') }}
