trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'tests'
    arguments: '-c Release'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: 'src/*.fsproj'
    includesymbols: true
    versioningScheme: 'off'
    verbosityPack: 'Quiet'