site_name: Yzl
repo_url: https://github.com/queil/yzl
site_url: https://queil.github.io/yzl
nav:
- Home: index.md
- API Reference:
  - index.md
  - reference/yzl-core-yzl.md
  - reference/yzl-core-operators.md
theme: 
  name: material
  palette:
    primary: teal
